from .dpi import truemove_air
from .. import usbhid

profile = {
    "name": "SteelSeries Rival 5",
    "models": [
        {
            "name": "SteelSeries Rival 5",
            "vendor_id": 0x1038,
            "product_id": 0x183C,
            "endpoint": 0,
        }
    ],
    "settings": {
        "sensitivity": {
            "label": "Sensibility presets",
            "description": "Set sensitivity preset (DPI)",
            "cli": ["-s", "--sensitivity"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x2D],
            "value_type": "multidpi_range_choice",
            "input_range": [100, 18000, 100],
            "output_choices": truemove_air.choices,
            "dpi_length_byte": 1,
            "first_preset": 0,
            "max_preset_count": 5,
            "default": "400, 800, 1200, 2400, 3200",
        },
        "polling_rate": {
            "label": "Polling rate",
            "description": "Set polling rate (Hz)",
            "cli": ["-p", "--polling-rate"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x2B],
            "value_type": "choice",
            "choices": {
                125: 0x04,
                250: 0x03,
                500: 0x02,
                1000: 0x01,
            },
            "default": 1000,
        },
        # Strip color setting example:
        # rivalcfg -z "11ff11; 22ff22; 66ff66; 33ff33; 77ff77; 44ff44; 88ff88; 55ff55; 99ff99; aaffaa"
        # This would color all LEDs (in a shade of green).
        "color": {
            "label": "LED color",
            "description": "Set the mouse LED color",
            "cli": ["-c", "--color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0xFF, 0x03],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "default": "000000; 000000; 000000; 000000; 000000; 000000; 000000; 000000; 000000; 000000",
        },
        "wheel_color": {
            "label": "Wheel LED color",
            "description": "Set the color of the wheel LED",
            "cli": ["-cw", "--wheel-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x01, 0x00],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#11ff11",
        },
        "top_left_color": {
            "label": "Top left LED color",
            "description": "Set the color of the top left LED",
            "cli": ["-ctl", "--top-left-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x02, 0x00],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#22ff22",
        },
        "top_right_color": {
            "label": "Top right LED color",
            "description": "Set the color of the top right LED",
            "cli": ["-ctr", "--top-right-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x04, 0x00],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#66ff66",
        },
        "middle1_left_color": {
            "label": "Middle1 left LED color",
            "description": "Set the color of the middle1 left LED",
            "cli": ["-cml1", "--middle1-left-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x08, 0x00],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#33ff33",
        },
        "middle1_right_color": {
            "label": "Middle1 right LED color",
            "description": "Set the color of the middle1 right LED",
            "cli": ["-cmr1", "--middle1-right-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x10, 0x00],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#77ff77",
        },
        "middle2_left_color": {
            "label": "Middle2 left LED color",
            "description": "Set the color of the middle2 left LED",
            "cli": ["-cml2", "--middle2-left-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x20, 0x00],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#44ff44",
        },
        "middle2_right_color": {
            "label": "Middle2 right LED color",
            "description": "Set the color of the middle2 right LED",
            "cli": ["-cmr2", "--middle2-right-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x40, 0x00],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#88ff88",
        },
        "bottom_left_color": {
            "label": "Bottom left LED color",
            "description": "Set the color of the bottom left LED",
            "cli": ["-cbl", "--bottom-left-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x80, 0x00],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#55ff55",
        },
        "bottom_right_color": {
            "label": "Bottom right LED color",
            "description": "Set the color of the bottom right LED",
            "cli": ["-cbr", "--bottom-right-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x00, 0x01],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#99ff99",
        },
        "logo_color": {
            "label": "Logo LED color",
            "description": "Set the color of the logo LED",
            "cli": ["-cl", "--logo-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x21, 0x00, 0x02],
            "value_type": "onestr_rgbcolor",
            "led_count": 10,
            "set_one_color": True,
            "default": "#aaffaa",
        },
        "reactive_color": {
            "label": "Reactive color",
            "description": "Set the color of the LEDs in reaction to a button click",
            "cli": ["-a", "--reactive-color"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x26],
            "value_type": "reactive_rgbcolor",
            "default": "off",
        },
        "led_brightness": {
            "label": "LED Brightness",
            "description": "Set the brightness of the LEDs",
            "cli": ["-l", "--led-brightness"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x23],
            "value_type": "choice",
            "choices": {
                100: 0x64,
                75: 0x32,
                50: 0x19,
                25: 0x0C,
                0: 0x00,
            },
            "default": 100,
        },
        "buttons_mapping": {
            "label": "Buttons mapping",
            "description": "Set the mapping of the buttonsX",
            "cli": ["-b", "--buttons"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x2A],
            "value_type": "buttons",
            "buttons": {
                "Button1": {"id": 0x01, "offset": 0x00, "default": "button1"},
                "Button2": {"id": 0x02, "offset": 0x05, "default": "button2"},
                "Button3": {"id": 0x03, "offset": 0x0A, "default": "button3"},
                "Button4": {"id": 0x04, "offset": 0x0F, "default": "button4"},
                "Button5": {"id": 0x05, "offset": 0x14, "default": "button5"},
                "Button6": {"id": 0x06, "offset": 0x19, "default": "disabled"},
                "Button7": {"id": 0x00, "offset": 0x1E, "default": "disabled"},
                "Button8": {"id": 0x00, "offset": 0x23, "default": "disabled"},
                "Button9": {"id": 0x00, "offset": 0x28, "default": "dpi"},
                "ScrollUp": {"id": 0x31, "offset": 0x2D, "default": "scrollup"},
                "ScrollDown": {"id": 0x32, "offset": 0x32, "default": "scrolldown"},
            },
            "button_field_length": 5,
            "button_disable": 0x00,
            "button_keyboard": 0x51,
            "button_multimedia": 0x61,
            "button_dpi_switch": 0x30,
            "button_scroll_up": None,
            "button_scroll_down": None,
            "default": "buttons(button1=button1; button2=button2; button3=button3; button4=button4; button5=button5; button6=disabled; button7=disabled; button8=disabled; button9=dpi; scrollup=scrollup; scrolldown=scrolldown; layout=qwerty)",
        },
        "rainbow_effect": {
            "label": "rainbow effect",
            "description": "Enable the rainbow effect (can be disabled by setting a color)",
            "cli": ["-e", "--rainbow-effect"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x22, 0xFF, 0x03],
            "value_type": "none",
        },
        "default_lighting": {
            "label": "Default lighting",
            "description": "Set default lighting at mouse startup, Reactive-color must be toggled separately!",
            "cli": ["-d", "--default-lighting"],
            "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
            "command": [0x27],
            "value_type": "choice",
            "choices": {
                "off": [0x00, 0x00, 0x00],
                "rainbow": [0x01, 0x00, 0x00],
            },
            "default": "rainbow",
        },
    },
    "save_command": {
        "report_type": usbhid.HID_REPORT_TYPE_OUTPUT,
        "command": [0x11, 0x00],
    },
}
